apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment  
  labels:
    app: node-app           
spec:
  replicas: 3           
  selector:
    matchLabels:
      app: node-app       
  template:
    metadata:
      labels:
        app: node-app      
    spec:
      containers:
      - name: node-app
        image: public.ecr.aws/q1t2i1c7/ahmed-m-farouk/eyego
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "100m"      
            memory: "128Mi"  
          limits:
            cpu: "200m"      
            memory: "256Mi"  