apiVersion: v1
kind: Pod
metadata:
  name: node-app-pod
spec:
  containers:
  - name: node-app-container
    image: public.ecr.aws/q1t2i1c7/ahmed-m-farouk/eyego
    ports:
      - containerPort: 3000
